"""empty message

Revision ID: cf61d9e67abc
Revises: c92aaca3a1c4
Create Date: 2021-07-07 10:49:52.121023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf61d9e67abc'
down_revision = 'c92aaca3a1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('recipe_reference', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'recipe_reference')
    # ### end Alembic commands ###
