"""empty message

Revision ID: f87dde3625b4
Revises: cf61d9e67abc
Create Date: 2021-07-10 21:51:00.774856

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f87dde3625b4'
down_revision = 'cf61d9e67abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients') as batch_op:
        batch_op.alter_column('ddd',
                              existing_type=sa.VARCHAR(length=2),
                              type_=sa.String(length=4),
                              existing_nullable=True)
        batch_op.alter_column('phonenumber',
                              existing_type=sa.VARCHAR(length=16),
                              type_=sa.String(length=10),
                              existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients') as batch_op:
        batch_op.alter_column('phonenumber',
                              existing_type=sa.String(length=10),
                              type_=sa.VARCHAR(length=16),
                              existing_nullable=True)
        batch_op.alter_column('ddd',
                              existing_type=sa.String(length=4),
                              type_=sa.VARCHAR(length=2),
                              existing_nullable=True)
    # ### end Alembic commands ###
